---@diagnostic disable: missing-fields
require("nvim-dap-repl-highlights").setup()

require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"c",
		"cpp",
		"lua",
		"vim",
		"rust",
		"python",
		"cmake",
		"css",
		"dockerfile",
		"git_config",
		"git_rebase",
		"gitattributes",
		"gitcommit",
		"gitignore",
		"http",
		"luadoc",
		"markdown",
		"markdown_inline",
		"regex",
		"rust",
		"scss",
		"yaml",
		"json",
		"yuck",
		"toml",
		"sxhkdrc",
		"sql",
		"typescript",
		"javascript",
		"svelte",
		"dap_repl",
		"bash",
		"glsl",
		"gleam",
	},
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = true,
	},
	autotag = {
		enable = true,
	},
	sync_install = true,
})
