require("autocommands.linting")
require("autocommands.startup")
require("autocommands.clang")
require("autocommands.filetype")
require("autocommands.delimiters")
require("autocommands.showkeys")
require("autocommands.headers")
